In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../dataset/Constitution Of India.csv")

In [3]:
df.shape

(456, 1)

In [4]:
df.columns

Index(['Articles'], dtype='object')

In [5]:
df.head(10)

                                            Articles
0  1. Name and territory of the Union\n(1) India,...
1  1. The territories of the States; the Union te...
2  2. Admission or establishment of new States: P...
3  2A. Sikkim to be associated with the Union Rep...
4  3. Formation of new States and alteration of a...
5  4. Laws made under Articles 2 and 3 to provide...
6  5. Citizenship at the commencement of the Cons...
7  6. Rights of citizenship of certain persons wh...
8  7. Rights of citizenship of certain migrants t...
9  8. Rights of citizenship of certain persons of...

In [8]:
idx = pd.read_csv("../dataset/Index.csv", encoding="latin1")

In [9]:
idx.shape

(27, 3)

In [10]:
idx.columns

Index(['Parts of the Indian Constitution', 'Subject Mentioned in the Part',
       'Articles in Indian Constitution'],
      dtype='object')

In [11]:
idx.head(10)

,Parts of the Indian Constitution,Subject Mentioned in the Part,Articles in Indian Constitution
0,Part I,Union & Its Territory,Article 1-4
1,Part II,Citizenship,Article 5-11
2,Part III,Fundamental Rights,Article 12-35
3,Part IV,Directive Principles,Article 36-51
4,Part IV A,Fundamental Duties,Article 51A
5,Part V,The Union,Article 52-151
6,Part VI,The States,Article 152-237
7,Part VII,"Note: 7th Amendment Act, 1956 repealed Part 7",
8,Part VIII,The Union Territories,Article 239-242
9,Part IX,The Panchayats,Article 243-243O